name: Build Hybris Operator Image
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.0'
      - uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      - uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - uses: actions/checkout@v2
      - name: Install Kubebuilder
        env:
          RELEASE_VERSION: 2.3.1
        run: |
          os=$(go env GOOS)
          arch=$(go env GOARCH)
          curl -L https://go.kubebuilder.io/dl/${RELEASE_VERSION}/${os}/${arch} | tar -xz -C /tmp/
          sudo mv /tmp/kubebuilder_${RELEASE_VERSION}_${os}_${arch} /usr/local/kubebuilder
      - name: Install Operator SDK
        env:
          RELEASE_VERSION: v1.6.1
        run: |
          curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk_linux_amd64
          chmod +x operator-sdk_linux_amd64 && sudo mkdir -p /usr/local/bin/ && sudo cp operator-sdk_linux_amd64 /usr/local/bin/operator-sdk && rm operator-sdk_linux_amd64
      - name: Build and Push Operator
        run: |
          export PATH=$PATH:/usr/local/kubebuilder/bin
          make docker-build docker-push
      - name: Build and Push Bundle
        run: |
          make bundle bundle-build bundle-push
      - name: Build and Push Index
        run: |
          make catalog-build catalog-push
